name: bugsnag-hs
version: 0.1.0.0
synopsis: A Bugsnag client for Haskell.
description: Please see the README at <https://github.com/jwoudenberg/bugsnag-hs>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2019 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/bugsnag-hs#readme
license: BSD3
license-file: LICENSE
category: Web
extra-doc-files:
- README.md
- CHANGELOG.md
library:
  dependencies:
  - aeson
  - auto-update
  - base
  - bytestring
  - cabal-file-th
  - http-client
  - http-types
  - stm
  - text
  - time
  - unordered-containers
  exposed-modules:
  - Network.Bugsnag
  source-dirs: src
tests:
  spec:
    dependencies:
    - aeson
    - base
    - bytestring
    - bugsnag-hs
    - hashable
    - text
    - unordered-containers
    main: Main.hs
    source-dirs:
    - test
