name: bugsnag-hs
version: 0.1.0.2
synopsis: A Bugsnag client for Haskell.
description: Please see the README at <https://github.com/jwoudenberg/bugsnag-hs>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2019 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/bugsnag-hs#readme
license-file: LICENSE
category: Web
github: jwoudenberg/bugsnag-hs
extra-doc-files:
- README.md
- CHANGELOG.md
data-files:
- test/sample-report.json
library:
  dependencies:
  - aeson >= 1.2.4.0 && < 1.6
  - auto-update >= 0.1.4 && < 0.2
  - base >= 4.10.1.0 && < 5
  - bytestring >= 0.10.8.2 && < 0.11
  - http-client >= 0.5.10 && < 0.7
  - stm >= 2.4.5.0 && < 2.6
  - text >= 1.2.3.0 && < 1.3
  - time >= 1.8.0.2 && < 1.11
  - unordered-containers >= 0.2.9.0 && < 0.3
  exposed-modules:
  - Network.Bugsnag
  - Data.Buffer
  source-dirs: src
tests:
  spec:
    dependencies:
    - aeson >= 1.2.4.0 && < 1.6
    - base >= 4.10.1.0 && < 5
    - bytestring >= 0.10.8.2 && < 0.11
    - bugsnag-hs
    - hedgehog >= 0.5.2 && < 2.0
    - stm >= 2.4.5.0 && < 2.6
    main: Main.hs
    source-dirs:
    - test
